version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: datascience
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  jupyter:
    image: jupyter/scipy-notebook:latest
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - "8888:8888"
    depends_on:
      - postgres
  
  streamlit:
    image: python:3.8
    command: bash -c "pip install streamlit pandas psycopg2 SQLAlchemy&& streamlit run app.py"
    volumes:
      - ./streamlit:/app
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    working_dir: /app
  
  mlflow:
    build: ./mlflow/
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
    depends_on:
      - postgres

volumes:
  postgres_data: